# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - '*' 
    exclude: 
    - '*'
    
pool: Pruebas Automatizadas UI
#  vmImage: POC

variables:
- group: Framework-Automatizaci贸n 

steps:  


- task: CmdLine@2
  inputs:
    script: START /B java -jar c:\Users\francisco.cleverit\selenium-server-standalone\selenium-server-standalone-3.141.59.jar -role hub -log log.txt
  displayName: 'Creaci贸n de HUB'

  
- task: CmdLine@2
  inputs:
    script: START /B java -Dwebdriver.edge.driver=C:\Users\francisco.cleverit\selenium-drivers\msedgedriver.exe -jar c:\Users\francisco.cleverit\selenium-server-standalone\selenium-server-standalone-3.141.59.jar -role node  -hub http://localhost:4444/grid/register  -browser "browserName=MicrosoftEdge, platform=WINDOWS, maxInstances=5"
  displayName: 'Creaci贸n de nodo Edge'


- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.4.0'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    noCache: true
    disableParallelProcessing: true

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
    createLogFile: true

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    key: '$(key)'   
    vsTestVersion: '16.0'
    testRunTitle: 'Ejecuci贸n de pruebas'
    diagnosticsEnabled: true
    collectDumpOn: 'always'
       

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:\EAAutoLogs'
    ArtifactName: 'File LOG'
    publishLocation: 'Container'
  condition: always()